vich_uploader:
    db_driver: orm

    mappings:
        avatar_img:
            uri_prefix: /uploads/images/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
